### ISSUE TITLE
OpenAI doesnt generate images.

### ISSUE THREAD

**Issue by raymerjacque** [BB31420/AI-Auto-Video-Generator#3]
image_generator.py", line 13, in generate_images
    response = openai.Image.create(
AttributeError: module 'openai' has no attribute 'Image'

**Comment by BB31420** [comment]
What steps should I follow to reproduce this error? Code is working on my end and API documentation is the same for OpenAI. I would try to delete your old API key from OpenAI and produce a new one. If that doesn't fix it, try cloning the repo again and start fresh. Let me know either way we'll figure this out. Thank you for bringing this up
