### ISSUE TITLE
How to create moving image?

### ISSUE THREAD

**Issue by nuh0058** [BB31420/AI-Auto-Video-Generator#4]
How to create moving image like your example video? https://www.youtube.com/watch?v=hV4t2yW-RUk

**Comment by BB31420** [comment]
Hello. I wasn't able to resolve a bug from the zoom feature version of the code. It is possible to zoompan with ffmpeg, the dependency used by moviepy and to apply effects to the images before they are concatenated to form the video with some minor updates.
