### ISSUE TITLE
How can we create captions?

### ISSUE THREAD

**Issue by TheMarketr** [BB31420/AI-Auto-Video-Generator#6]
I managed to make this amazing script work with DALLE-3, but now I want to know how can I add captions to the videos?
I saw some functions in the documentation for the font, but I'm not sure where they should go.
Any help?

**Comment by BB31420** [comment]
Thanks for bringing this up. The code at one time printed the transcript/story on the screen in one block of text. I will update the documentation to remove this part. I added a few updates to the code tonight that should allow it to work without much hassle now. 

I will also work on adding in this functionality or would look forward to seeing your implementation.

Cheers,

**Comment by BB31420** [comment]
I added the ability to add captions and updated the docs.
